CREATE TABLE IF NOT EXISTS PAUTA
(
    ID     SERIAL       NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    STATUS VARCHAR(15) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS VOTACAO
(
    ID           SERIAL NOT NULL,
    ASSOCIADO_ID INTEGER NOT NULL,
    VOTO         BOOLEAN NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SESSAO_VOTACAO
(
    ID               SERIAL NOT NULL,
    PAUTA_ID         INTEGER,
    STATUS           VARCHAR(15) NOT NULL,
    DATA_HORA_INICIO TIMESTAMP NOT NULL,
    DATA_HORA_FIM    TIMESTAMP NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (PAUTA_ID) REFERENCES PAUTA (ID)
);
