CREATE DATABASE "backend-cooperativa-db";

\c "backend-cooperativa-db";

CREATE TABLE PAUTA
(
    ID     SERIAL       NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);


CREATE TABLE ASSOCIADO
(
    ID SERIAL NOT NULL,
    PRIMARY KEY (ID)
);


CREATE TABLE VOTACAO
(
    ID           SERIAL NOT NULL,
    PAUTA_ID     NUMBER NOT NULL,
    ASSOCIADO_ID NUMBER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (PAUTA_ID) REFERENCES PAUTA (ID),
    FOREIGN KEY (ASSOCIADO_ID) REFERENCES ASSOCIADO (ID)
);
