CREATE TABLE IF NOT EXISTS PAUTA
(
    ID              SERIAL NOT NULL,
    TITULO          VARCHAR(100) NOT NULL,
    STATUS          VARCHAR(15) NOT NULL,
    TOTAL_VOTOS     INTEGER,
    TOTAL_VOTOS_SIM INTEGER,
    TOTAL_VOTOS_NAO INTEGER,
    RESULTADO       VARCHAR(15),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SESSAO
(
    ID               SERIAL NOT NULL,
    PAUTA_ID         INTEGER,
    STATUS           VARCHAR(15) NOT NULL,
    DATA_HORA_INICIO TIMESTAMP NOT NULL,
    DATA_HORA_FIM    TIMESTAMP NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (PAUTA_ID) REFERENCES PAUTA (ID)
);

CREATE TABLE IF NOT EXISTS VOTACAO
(
    ID           SERIAL NOT NULL,
    SESSAO_ID    INTEGER,
    ASSOCIADO_ID INTEGER NOT NULL,
    VOTO         BOOLEAN NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (SESSAO_ID) REFERENCES SESSAO (ID)
);
