version: "3"

services:

  backend-cooperativa:
    build: ../
    container_name: backend-cooperativa
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/backend-cooperativa-db"
      - "SPRING_RABBITMQ_HOST=rabbitmq"
      - "TZ=America/Sao_Paulo"
    networks:
      - backend-cooperativa
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgresql:
        condition: service_healthy

  postgresql:
    image: "postgres:14.1"
    ports:
      - "5432:5432"
    networks:
      - backend-cooperativa
    volumes:
      - ./sql/iniciar-banco-dados.sql:/docker-entrypoint-initdb.d/iniciar-banco-dados.sql
    environment:
      - "POSTGRES_DB=backend-cooperativa-db"
      - "POSTGRES_USER=backend-cooperativa-db"
      - "POSTGRES_PASSWORD=backend-cooperativa-db"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backend-cooperativa-db"]
      interval: 5s
      timeout: 5s
      retries: 6

  rabbitmq:
    image: rabbitmq:3.11.8-management
    mem_limit: 512m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend-cooperativa
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 2s
      retries: 60

networks:
  backend-cooperativa:
    driver: bridge
